version: '3.8'
services:
  mongo:
    image: mongo
    ports:
    - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: jargon
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
    - ./db-data/mongo/:/data/db

  postgres:
    image: bitnami/postgresql
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: jargon
    volumes:
    - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: